pipeline {
   agent any
   stages {
     stage('Build'){
          steps{
            sh 'mkdir dir3'
}
}
      stage('Test'){
          steps{
            sh 'mkdir dir4'
}
}
      stage('Deploy') {
         steps{
           sh 'mkdir dir5'
}   
}
}
}

